# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestPCHOME():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_pCHOME(self):
    self.driver.get("https://24h.pchome.com.tw/")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.CSS_SELECTOR, ".l-header__siteSearchInput").click()
    self.driver.find_element(By.CSS_SELECTOR, ".l-header__siteSearchInput").click()
    self.driver.find_element(By.CSS_SELECTOR, ".l-header__siteSearchInput").send_keys("Whoscall")
    self.driver.find_element(By.CSS_SELECTOR, ".l-header__searchBar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn__square--primary").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Whoscall象卡來市話版 家中防詐神器（免服務年費與一年主機保固）").click()
    self.vars["win9813"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9813"])

    Price = self.driver.find_element(By.CSS_SELECTOR, ".o-prodPrice__price")
    print(Price)

    assert(Price == "$1499")

    charts = self.driver.find_element(By.CSS_SELECTOR, ".c-prodSpecs")
    action = ActionChains(self.driver)
    action.move_to_element(charts).perform()

    self.driver.get_screenshot_as_file("2330.png")

    self.driver.close()
